// 公共 API 入口（供测试 / 第三方使用）
export * from './core/paths.js';
export * from './core/frontmatter.js';
export * from './core/status.js';
export * from './core/validate.js';
export * from './core/spec-io.js';
export * from './core/spec-policy.js';
export * from './core/project-snapshot.js';
export * from './core/archive-plan.js';
export * from './core/agents.js';
export * from './core/audit-events.js';
export * from './core/repository.js';
export * from './core/usability.js';
export * from './core/invariants.js';
export * from './core/verify.js';
export * from './core/task-completion.js';
export { completeTask } from './core/task.js';
export * from './core/spec-sections.js';
export * from './core/integrity.js';
export * from './core/integrity-exemptions.js';
export * from './core/remediation.js';
export * from './core/lifecycle.js';
export * from './core/reconciliation.js';
export * from './core/transaction.js';
export * from './schemas/spec.js';
